### ISSUE TITLE
JupyterLab dependency incorrectly specified

### ISSUE THREAD

**Issue by ZelphirKaltstahl** [jupyterlab-contrib/jupyterlab_code_formatter#328]
I think there is a mistake with specifying JupyterLab as a dependency incorrectly.

When I install `jupyterlab-code-formatter = "==2.2.1"` with `juypterlab = "==3.1.13"` using `pipenv`, I receive no warning at all, that these versions are not compatible. In fact, I see JupyterLab being wrongly specified here <https://github.com/ryantam626/jupyterlab_code_formatter/blob/4b68e0c4ee45b1a4c985bbd8d6ebc1a138e2cc82/pyproject.toml#L40>, while JupyterLab itself tells me, that `jupyterlab-code-formatter` at version `2.2.1` is incompatible, when I run `jupyter labextension list`:

```
"jupyterlab_code_formatter@2.2.1" is not compatible with the current JupyterLab
Conflicting Dependencies:
JupyterLab                  Extension       Package
>=3.1.12 <3.2.0             >=3.6.0 <4.0.0||>=4.0.0 <4.1.0@jupyterlab/application
>=3.1.12 <3.2.0             >=3.6.0 <4.0.0||>=4.0.0 <4.1.0@jupyterlab/fileeditor
>=3.1.12 <3.2.0             >=3.6.0 <4.0.0||>=4.0.0 <4.1.0@jupyterlab/mainmenu
>=3.1.12 <3.2.0             >=3.6.0 <4.0.0||>=4.0.0 <4.1.0@jupyterlab/settingregistry
```

This package should specify its dependency properly, so that users notice this mismatch in dependencies as early as possible, which is when installing the Python package from PyPI.

Now I also cannot easily figure out, which version of `jupyterlab-code-formatter` I have to use instead, because I first have to create a complete setup, install the extension etc. and then run `jupyter labextension list` again, to find out, whether I installed a compatible version.

**Comment by krassowski** [comment]
Closing as fixed by https://github.com/jupyterlab-contrib/jupyterlab_code_formatter/pull/346 (released in [v3.0.0](https://github.com/jupyterlab-contrib/jupyterlab_code_formatter/releases/tag/v3.0.0)).
