### ISSUE TITLE
Support ruff formatter

### ISSUE THREAD

**Issue by devmcp** [jupyterlab-contrib/jupyterlab_code_formatter#330]
As of [ruff v0.1.2](https://github.com/astral-sh/ruff/releases/tag/v0.1.2) it supports formatting as well as linting. It would be great to support this natively.

There is a walkthrough [here](https://gist.github.com/jbwhit/eecdd1cac2756df85ad165f437445b0b) with a workaround, but I couldn't get it to work (I get "Formatter ruff_format not found" despite adding it to the jupyterlab config and restarting jupyterlab).

**Comment by samsja** [comment]
any news on this issue ? Big fan of this project and ruff is great

**Comment by axeltlarsson** [comment]
I'd love for this project to natively support ruff too.

Meanwhile I'm trying out the workaround linked above, but having some issues with the fact that formatting through jyputerlab_code_formatter doesn't format the same way as if running `ruff format` from the command line... Mildly infuriating to say the least, and makes it really difficult to use in CI. Any ideas why? It should use the same binary and version, it's just one goes through jyputerlab_code_formatter and the other doesn't as far as I can tell.

**Comment by krassowski** [comment]
Closing as fixed by https://github.com/jupyterlab-contrib/jupyterlab_code_formatter/pull/333
