### ISSUE TITLE
Unable to find default formatters to use

### ISSUE THREAD

**Issue by elinormed** [jupyterlab-contrib/jupyterlab_code_formatter#335]
<img width="469" alt="image" src="https://github.com/ryantam626/jupyterlab_code_formatter/assets/160482690/0ef36788-e38c-45a0-9538-1b76d0e17a39">

I pip install isort and black, they're the default, yet it still cannot find formatters...

env: 

 % lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy

 % pip list      
Package                               Version
------------------------------------- ---------------------
aiohttp                               3.9.3
aiosignal                             1.3.1
alembic                               1.13.1
anndata                               0.9.2
annotated-types                       0.6.0
anyio                                 3.7.1
arel                                  0.3.0
argon2-cffi                           23.1.0
argon2-cffi-bindings                  21.2.0
asttokens                             2.4.1
async-asgi-testclient                 1.4.11
async-generator                       1.10
async-timeout                         4.0.3
attrs                                 23.2.0
Babel                                 2.14.0
beautifulsoup4                        4.12.3
bidict                                0.23.1
black                                 24.3.0
bleach                                6.1.0
blinker                               1.4
cacheout                              0.14.1
cachetools                            4.2.4
certifi                               2023.11.17
certipy                               0.1.3
cffi                                  1.16.0
chardet                               4.0.0
charset-normalizer                    3.2.0
cli-helpers                           2.2.1
click                                 8.0.3
colorama                              0.4.4
comm                                  0.2.1
configobj                             5.0.6
contourpy                             1.2.0
crcmod                                1.7
cryptography                          42.0.2
cssutils                              2.9.0
cycler                                0.12.1
dataframe-image                       0.2.3
dataset-tools                         0.0.33
db-dtypes                             1.1.1
dbus-python                           1.2.18
debugpy                               1.8.0
decorator                             5.1.1
defusedxml                            0.7.1
Deprecated                            1.2.14
distinctipy                           1.3.4
distlib                               0.3.8
distro                                1.7.0
entrypoints                           0.4
exceptiongroup                        1.2.0
executing                             2.0.1
fastapi                               0.109.0
fastjsonschema                        2.19.1
ffmpeg-python                         0.2.0
filelock                              3.13.1
fonttools                             4.49.0
frozenlist                            1.4.1
fsspec                                2023.6.0
future                                0.18.3
gcsfs                                 2023.6.0
gdown                                 5.1.0
geojson                               3.1.0
gitdb                                 4.0.11
GitPython                             3.1.42
giturlparse                           0.12.0
google-api-core                       2.17.1
google-auth                           2.27.0
google-auth-oauthlib                  1.2.0
google-cloud-bigquery                 3.11.4
google-cloud-core                     2.4.1
google-cloud-storage                  2.14.0
google-crc32c                         1.5.0
google-resumable-media                2.7.0
googleapis-common-protos              1.62.0
greenlet                              3.0.3
grpcio                                1.62.0
grpcio-status                         1.62.0
gscache                               2.0.2
h11                                   0.14.0
h5py                                  3.10.0
html2image                            2.0.4.3
httplib2                              0.20.2
httptools                             0.6.1
humanize                              4.8.0
idna                                  3.6
imageio                               2.34.0
imagesize                             1.4.1
importlib-metadata                    6.1.0
imutils                               0.5.4
inflect                               7.0.0
ipykernel                             6.29.0
ipython                               8.21.0
ipython-genutils                      0.2.0
isort                                 5.13.2
jaraco.classes                        3.3.0
jedi                                  0.19.1
jeepney                               0.8.0
Jinja2                                3.1.3
joblib                                1.3.2
json5                                 0.9.14
jsonpatch                             1.33
jsonpointer                           2.4
jsonschema                            4.20.0
jsonschema-specifications             2023.12.1
jupyter_client                        7.4.9
jupyter_core                          5.7.1
jupyter-dagit-proxy                   2.0.1
jupyter-rsession-proxy                2.0.1
jupyter-server                        1.24.0
jupyter_server_proxy                  4.1.0
jupyter-telemetry                     0.1.0
jupyter-vscode-proxy                  0.2
jupyterhub                            2.3.1
jupyterlab                            3.4.5
jupyterlab_code_formatter             2.2.1
jupyterlab_pygments                   0.3.0
jupyterlab_server                     2.25.2
keyring                               24.3.0
keyrings.google-artifactregistry-auth 1.1.2
kiwisolver                            1.4.5
launchpadlib                          1.10.16
lazr.restfulclient                    0.14.4
lazr.uri                              1.0.6
lazy_loader                           0.3
line-profiler                         4.1.2
lxml                                  5.1.0
Mako                                  1.3.2
markdown-it-py                        3.0.0
MarkupSafe                            2.1.4
matplotlib                            3.8.3
matplotlib-inline                     0.1.6
mdurl                                 0.1.2
memory-profiler                       0.61.0
mistune                               3.0.2
more-itertools                        10.2.0
multidict                             6.0.4
mypy-extensions                       1.0.0
natsort                               8.4.0
nbclassic                             1.0.0
nbclient                              0.9.0
nbconvert                             7.14.2
nbformat                              5.9.2
nest-asyncio                          1.6.0
networkx                              3.2.1
notebook                              6.5.6
notebook_shim                         0.2.3
numerize                              0.12
numpy                                 1.23.5
oauthlib                              3.2.2
opencv-python                         4.9.0.80
packaging                             23.0
pamela                                1.1.0
pandas                                2.1.4
pandocfilters                         1.5.1
parameterized                         0.9.0
parso                                 0.8.3
pathspec                              0.12.1
pendulum                              2.1.2
pexpect                               4.9.0
pgcli                                 3.3.1
pgspecial                             1.11.10
pillow                                10.2.0
pip                                   22.0.2
platformdirs                          4.2.0
pluggy                                1.4.0
prometheus-client                     0.19.0
prompt-toolkit                        3.0.43
proto-plus                            1.23.0
protobuf                              4.25.3
psutil                                5.9.8
psycopg2                              2.9.2
PTable                                0.9.2
ptyprocess                            0.7.0
pure-eval                             0.2.2
pyarrow                               13.0.0
pyasn1                                0.5.1
pyasn1-modules                        0.3.0
pychebfun                             0.3
pycocotools                           2.0.7
pycparser                             2.21
pydantic                              2.5.0
pydantic_core                         2.14.1
pydicom                               2.4.4
Pygments                              2.17.2
PyGObject                             3.42.1
PyJWT                                 2.3.0
Pympler                               1.0.1
pynrrd                                0.4.3
pyOpenSSL                             24.0.0
pyparsing                             2.4.7
PySocks                               1.7.1
python-apt                            2.4.0+ubuntu2
python-celldb-client                  2.1.7
python-dateutil                       2.8.2
python-debian                         0.1.43+ubuntu1.1
python-dotenv                         1.0.0
python-json-logger                    2.0.7
python-magic                          0.4.27
python-multipart                      0.0.5
pytz                                  2024.1
pytzdata                              2020.1
PyYAML                                6.0
pyzmq                                 24.0.1
radian                                0.6.4
ranger-fm                             1.9.3
rchitect                              0.3.40
referencing                           0.33.0
requests                              2.31.0
requests-oauthlib                     1.3.1
requests-toolbelt                     0.10.1
rich                                  13.7.0
rpds-py                               0.17.1
rsa                                   4.9
ruamel.yaml                           0.18.5
ruamel.yaml.clib                      0.2.8
scikit-image                          0.22.0
scipy                                 1.12.0
SecretStorage                         3.3.3
Send2Trash                            1.8.2
setproctitle                          1.2.2
setuptools                            59.6.0
shapely                               2.0.2
simpervisor                           1.0.0
SimpleITK                             2.3.1
six                                   1.16.0
smmap                                 5.0.1
sniffio                               1.3.0
soupsieve                             2.5
SQLAlchemy                            2.0.25
sqlparse                              0.4.2
stack-data                            0.6.3
starlette                             0.35.1
stringcase                            1.2.0
supervisely                           6.73.34
tabulate                              0.8.9
tasklogger                            1.2.0
terminado                             0.18.0
terminaltables                        3.1.0
tifffile                              2024.2.12
tinycss2                              1.2.1
titlecase                             2.4
tomli                                 2.0.1
tornado                               6.4
tqdm                                  4.65.2
traitlets                             5.14.1
trimesh                               3.23.5
typing_extensions                     4.9.0
tzdata                                2024.1
UNKNOWN                               0.0.0b1.dev2+gc01b9cb
urllib3                               1.26.15
uvicorn                               0.27.1
uvloop                                0.19.0
varname                               0.13.0
virtualenv                            20.25.1
wadllib                               1.3.6
watchfiles                            0.21.0
wcwidth                               0.2.13
webencodings                          0.5.1
websocket-client                      1.7.0
websockets                            10.4
wheel                                 0.37.1
wrapt                                 1.16.0
xmltodict                             0.13.0
yarl                                  1.9.4
zipp                                  3.17.0

**Comment by sntgluca** [comment]
Same error here...

I tried with a couple of options with no success, such as

```json
{
    "formatOnSave": false,
    "suppressFormatterErrors" : true,
    "suppressFormatterErrorsIFFAutoFormatOnSave": false,
}
```

Anyone experiencing anything similar?
