### ISSUE TITLE
Default formatter not found

### ISSUE THREAD

**Issue by noushinquazi** [jupyterlab-contrib/jupyterlab_code_formatter#336]
I followed the conda installation instructions and went ahead and also installed the suggested formatters (black, isort, autopep8, etc) but after rebuilding jupyter lab and attempting to format an example cell I get the error "Jupyterlab Code Formatter Error
Unable to find default formatters to use, please file an issue on GitHub." When invoke the command palette and select "Apply Isort Formatter", for example, I get a different error message "Jupyterlab Code Formatter Error 'NoneType' object has no attribute 'startswith'".

**Comment by sntgluca** [comment]
Hi! It feels #335 and #336 are about the same topic? Am I wrong?

**Comment by krassowski** [comment]
Right, let's close it in favour of #335. Thank you!
